name: run-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Adjust if using a different dependency manager

    - name: Run pipeline
      run: |
        chmod +x pipeline.sh
        ./pipeline.sh
      env:
        run-test: true

    - name: Run tests
      run: |
        chmod +x tests.sh
        ./tests.sh
      env:
        run-test: true
