name: Run Tests

on:
    push:
        branches:
        - main
        paths:
        - project/**

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v4.6.0
          with:
            python-version: 3.11
        
        - name: Install dependencies
          run: pip install -r ./project/requirements.txt
