name: Run Tests

on:
    push:
        branches:
        - main
        paths:
        - project/**

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v4.6.0
          with:
            python-version: 3.11

        
        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt  # Adjust if using a different dependency manager

        
        - name: Make the pipeline script executable
          run: chmod +x ./project/pipeline.sh
            
        - name: Run pipeline script
          run: ./project/pipeline.sh

        - name: Make the test script executable
          run: chmod +x ./project/tests.sh
            
        - name: Run test script
          run: ./project/tests.sh
